name: testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Xcode select
        run: sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'
      - name: Build
        run: swift build
      - name: Test
        run: |
          swift test --enable-code-coverage
          xcrun llvm-cov export -format="lcov" .build/debug/EmailValidationPackageTests.xctest/Contents/MacOS/EmailValidationPackageTests -instr-profile .build/debug/codecov/default.profdata -ignore-filename-regex='Tests.swift' -ignore-filename-regex='EmailValidationMacros.swift' > info.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v2